from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(820, 615)
        MainWindow.setWindowIcon(QIcon("icon/window.ico"))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 801, 491))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")

        self.katalog = QtWidgets.QWidget()
        self.katalog.setObjectName("katalog")

        self.KtableWidget = QtWidgets.QTableWidget(self.katalog)
        self.KtableWidget.setGeometry(QtCore.QRect(10, 51, 771, 491))
        self.KtableWidget.setObjectName("KtableWidget")
        self.KtableWidget.setSortingEnabled(True)
        self.KtableWidget.setColumnCount(6)
        self.KtableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.KtableWidget.setHorizontalHeaderItem(5, item)
        self.KtableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.KtableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.KtableWidget.setAlternatingRowColors(True)
        self.KtableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.KtableWidget.horizontalHeader().setMinimumSectionSize(0)

        self.lineEditK = QtWidgets.QLineEdit(self.katalog)
        self.lineEditK.setGeometry(QtCore.QRect(10, 20, 641, 20))
        self.lineEditK.setText("")
        self.lineEditK.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineEditK.setObjectName("lineEditK")

        self.Ksearch = QtWidgets.QPushButton(self.katalog)
        self.Ksearch.setGeometry(QtCore.QRect(660, 20, 71, 23))
        self.Ksearch.setObjectName("Ksearch")

        self.pushDel = QtWidgets.QPushButton(self.katalog)
        self.pushDel.setGeometry(QtCore.QRect(740, 20, 41, 23))
        self.pushDel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/deltext.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDel.setIcon(icon)
        self.pushDel.setObjectName("pushDel")
        self.tabWidget.addTab(self.katalog, "")
        #
        # Create Page Reader
        #
        self.reader = QtWidgets.QWidget()
        self.reader.setObjectName("reader")

        self.RtableWidget = QtWidgets.QTableWidget(self.reader)
        self.RtableWidget.setGeometry(QtCore.QRect(10, 50, 771, 491))
        self.RtableWidget.setObjectName("RtableWidget")
        self.RtableWidget.setSortingEnabled(True)
        self.RtableWidget.setColumnCount(6)
        self.RtableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RtableWidget.setHorizontalHeaderItem(5, item)
        self.RtableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.RtableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.RtableWidget.setAlternatingRowColors(True)
        self.RtableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.RtableWidget.horizontalHeader().setMinimumSectionSize(0)

        self.Ksearch_2 = QtWidgets.QPushButton(self.reader)
        self.Ksearch_2.setGeometry(QtCore.QRect(660, 20, 71, 23))
        self.Ksearch_2.setObjectName("Ksearch_2")

        self.RlineEdit = QtWidgets.QLineEdit(self.reader)
        self.RlineEdit.setGeometry(QtCore.QRect(10, 20, 641, 20))
        self.RlineEdit.setText("")
        self.RlineEdit.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.RlineEdit.setObjectName("RlineEdit")

        self.Rdeltext = QtWidgets.QPushButton(self.reader)
        self.Rdeltext.setGeometry(QtCore.QRect(740, 20, 41, 23))
        self.Rdeltext.setText("")
        self.Rdeltext.setIcon(icon)
        self.Rdeltext.setObjectName("Rdeltext")

        self.tabWidget.addTab(self.reader, "")
        #
        # Create Page publisher
        #
        self.publisher = QtWidgets.QWidget()
        self.publisher.setObjectName("publisher")

        self.lineSearch = QtWidgets.QLineEdit(self.publisher)
        self.lineSearch.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.lineSearch.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineSearch.setObjectName("lineSearch")

        self.Asearch = QtWidgets.QPushButton(self.publisher)
        self.Asearch.setGeometry(QtCore.QRect(180, 20, 51, 23))
        self.Asearch.setObjectName("Asearch")

        self.tableWidgetPublic = QtWidgets.QTableWidget(self.publisher)
        self.tableWidgetPublic.setGeometry(QtCore.QRect(10, 50, 221, 411))
        self.tableWidgetPublic.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetPublic.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetPublic.setRowCount(0)
        self.tableWidgetPublic.setColumnCount(2)
        self.tableWidgetPublic.setObjectName("tableWidgetPublic")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPublic.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPublic.setHorizontalHeaderItem(1, item)
        self.tableWidgetPublic.setAlternatingRowColors(True)
        self.tableWidgetPublic.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tableWidgetPublic.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidgetPublic.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        self.Check_ID = QtWidgets.QLabel(self.publisher)
        self.Check_ID.setObjectName(u"Check_ID")
        self.Check_ID.setEnabled(False)
        self.Check_ID.setGeometry(QtCore.QRect(270, 60, 21, 16))

        self.label = QtWidgets.QLabel(self.publisher)
        self.label.setGeometry(QtCore.QRect(260, 40, 65, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 60, 461, 20))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_4.setBaseSize(QtCore.QSize(461, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.label_2 = QtWidgets.QLabel(self.publisher)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 50, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_5.setGeometry(QtCore.QRect(270, 110, 171, 20))
        self.lineEdit_5.setMaxLength(50)
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.label_3 = QtWidgets.QLabel(self.publisher)
        self.label_3.setGeometry(QtCore.QRect(460, 90, 44, 18))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_6.setGeometry(QtCore.QRect(470, 110, 161, 20))
        self.lineEdit_6.setMaxLength(30)
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.lineEdit_7 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_7.setGeometry(QtCore.QRect(270, 160, 171, 20))
        self.lineEdit_7.setMaxLength(4)
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.label_4 = QtWidgets.QLabel(self.publisher)
        self.label_4.setGeometry(QtCore.QRect(260, 140, 60, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.publisher)
        self.label_5.setGeometry(QtCore.QRect(260, 190, 59, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.lineEdit_8 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 210, 461, 20))
        self.lineEdit_8.setMaxLength(11)
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.label_6 = QtWidgets.QLabel(self.publisher)
        self.label_6.setGeometry(QtCore.QRect(260, 240, 37, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.lineEdit_9 = QtWidgets.QLineEdit(self.publisher)
        self.lineEdit_9.setGeometry(QtCore.QRect(270, 260, 461, 20))
        self.lineEdit_9.setMaxLength(327)
        self.lineEdit_9.setObjectName("lineEdit_9")

        self.textEdit = QtWidgets.QTextEdit(self.publisher)
        self.textEdit.setGeometry(QtCore.QRect(270, 310, 461, 151))
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")

        self.label_7 = QtWidgets.QLabel(self.publisher)
        self.label_7.setGeometry(QtCore.QRect(260, 290, 68, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.line = QtWidgets.QFrame(self.publisher)
        self.line.setGeometry(QtCore.QRect(223, 20, 41, 441))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.publisher, "")
        #
        # Create Page delivery
        #
        self.delivery = QtWidgets.QWidget()
        self.delivery.setObjectName("delivery")

        self.tableWidget_2 = QtWidgets.QTableWidget(self.delivery)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 40, 581, 421))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setSortingEnabled(True)
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.tableWidget_2.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        #
        # Create groupBox lending books
        #
        self.groupBoxEx = QtWidgets.QGroupBox(self.delivery)
        self.groupBoxEx = QtWidgets.QGroupBox(self.delivery)
        self.groupBoxEx.setGeometry(QtCore.QRect(600, 10, 181, 221))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.groupBoxEx.setFont(font)

        self.label_8 = QtWidgets.QLabel(self.groupBoxEx)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QtCore.QRect(10, 30, 87, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_8.setFont(font)

        self.BookEx = QtWidgets.QComboBox(self.groupBoxEx)
        self.BookEx.setObjectName(u"BookEx")
        self.BookEx.setGeometry(QtCore.QRect(20, 50, 151, 22))

        self.label_9 = QtWidgets.QLabel(self.groupBoxEx)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QtCore.QRect(10, 80, 87, 17))
        self.label_9.setFont(font)

        self.ReaderEx = QtWidgets.QComboBox(self.groupBoxEx)
        self.ReaderEx.setObjectName(u"ReaderEx")
        self.ReaderEx.setGeometry(QtCore.QRect(20, 100, 151, 22))
        self.ReaderEx.setFont(font)
        self.ReaderEx.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.dateTimeEdit_delivery = QtWidgets.QDateTimeEdit(self.groupBoxEx)
        self.dateTimeEdit_delivery.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit_delivery.setGeometry(QtCore.QRect(20, 160, 151, 22))
        self.dateTimeEdit_delivery.setDateTime(QtCore.QDateTime.currentDateTime())
        self.dateTimeEdit_delivery.setDisplayFormat("dd.MM.yyyy hh:mm")

        self.label_10 = QtWidgets.QLabel(self.groupBoxEx)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QtCore.QRect(10, 140, 89, 17))
        self.label_10.setFont(font)

        self.pushButton_2 = QtWidgets.QPushButton(self.groupBoxEx)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.pushButton_2.setFont(font)

        #
        # Create groupBox return of reader
        #
        self.groupBox_Rec = QtWidgets.QGroupBox(self.delivery)
        self.groupBox_Rec.setGeometry(QtCore.QRect(600, 310, 181, 111))

        self.dateTimeEdit_Vozvrat = QtWidgets.QDateTimeEdit(self.groupBox_Rec)
        self.dateTimeEdit_Vozvrat.setGeometry(QtCore.QRect(20, 50, 151, 22))
        self.dateTimeEdit_Vozvrat.setObjectName("dateTimeEdit_Vozvrat")
        self.dateTimeEdit_Vozvrat.setDateTime(QtCore.QDateTime.currentDateTime())
        self.dateTimeEdit_Vozvrat.setDisplayFormat("dd.MM.yyyy hh:mm")

        self.label_16 = QtWidgets.QLabel(self.groupBox_Rec)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 103, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_Rec)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 80, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.lineEdit_delivery = QtWidgets.QLineEdit(self.delivery)
        self.lineEdit_delivery.setObjectName("lineEdit_delivery")
        self.lineEdit_delivery.setGeometry(QtCore.QRect(10, 10, 511, 20))
        self.lineEdit_delivery.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)

        self.Search_Butt = QtWidgets.QPushButton(self.delivery)
        self.Search_Butt.setObjectName("Search_Butt")
        self.Search_Butt.setGeometry(QtCore.QRect(530, 10, 61, 23))

        self.tabWidget.addTab(self.delivery, "")

        self.label_Kdelete = QtWidgets.QLabel(self.centralwidget)
        self.label_Kdelete.setEnabled(True)
        self.label_Kdelete.setGeometry(QtCore.QRect(90, 70, 50, 13))
        self.label_Kdelete.setObjectName("label_Kdelete")

        self.Knew = QtWidgets.QPushButton(self.centralwidget)
        self.Knew.setEnabled(True)
        self.Knew.setGeometry(QtCore.QRect(20, 10, 61, 61))
        self.Knew.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Knew.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Knew.setAutoFillBackground(False)
        self.Knew.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Knew.setIcon(icon1)
        self.Knew.setIconSize(QtCore.QSize(64, 64))
        self.Knew.setObjectName("Knew")

        self.label_Ksave = QtWidgets.QLabel(self.centralwidget)
        self.label_Ksave.setEnabled(True)
        self.label_Ksave.setGeometry(QtCore.QRect(160, 70, 55, 13))
        self.label_Ksave.setObjectName("label_Ksave")

        self.Kdelete = QtWidgets.QPushButton(self.centralwidget)
        self.Kdelete.setEnabled(False)
        self.Kdelete.setGeometry(QtCore.QRect(90, 10, 61, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Kdelete.setIcon(icon2)
        self.Kdelete.setIconSize(QtCore.QSize(48, 48))
        self.Kdelete.setObjectName("Kdelete")

        self.Ksave = QtWidgets.QPushButton(self.centralwidget)
        self.Ksave.setEnabled(True)
        self.Ksave.setGeometry(QtCore.QRect(160, 10, 61, 61))
        self.Ksave.setIconSize(QtCore.QSize(40, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Ksave.setIcon(icon3)
        self.Ksave.setIconSize(QtCore.QSize(40, 40))
        self.Ksave.setObjectName("Ksave")

        self.label_Kadd = QtWidgets.QLabel(self.centralwidget)
        self.label_Kadd.setEnabled(True)
        self.label_Kadd.setGeometry(QtCore.QRect(20, 70, 50, 13))
        self.label_Kadd.setObjectName("label_Kadd")

        self.ExportButt = QtWidgets.QPushButton(self.centralwidget)
        self.ExportButt.setEnabled(True)
        self.ExportButt.setGeometry(QtCore.QRect(280, 10, 61, 61))
        self.ExportButt.setIconSize(QtCore.QSize(48, 48))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExportButt.setIcon(icon4)
        self.ExportButt.setIconSize(QtCore.QSize(48, 48))
        self.ExportButt.setObjectName("ExportButt")

        self.label_export = QtWidgets.QLabel(self.centralwidget)
        self.label_export.setEnabled(True)
        self.label_export.setGeometry(QtCore.QRect(280, 70, 89, 13))
        self.label_export.setObjectName("label_export")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEditK)
        MainWindow.setTabOrder(self.lineEditK, self.Ksearch)
        MainWindow.setTabOrder(self.Ksearch, self.KtableWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Введение библиотеки"))

        item = self.KtableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.KtableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название книги"))
        item = self.KtableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Автор"))
        item = self.KtableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Жанр"))
        item = self.KtableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата публикации"))
        item = self.KtableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Издательство"))
        self.lineEditK.setPlaceholderText(_translate("MainWindow", "поле поиска"))
        self.Ksearch.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.katalog), _translate("MainWindow", "Каталог книг"))

        item = self.RtableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.RtableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.RtableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.RtableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.RtableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.RtableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Телефон"))
        self.Ksearch_2.setText(_translate("MainWindow", "Поиск"))
        self.RlineEdit.setPlaceholderText(_translate("MainWindow", "поле поиска"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reader), _translate("MainWindow", "Читатели"))
        self.lineSearch.setPlaceholderText(_translate("MainWindow", "поле поиска"))
        self.Search_Butt.setText(_translate("MainWindow", "Поиск"))
        self.lineEdit_delivery.setPlaceholderText(_translate("MainWindow", "поле поиска"))
        self.Asearch.setText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Название издательства или ФИО издателя"))
        self.label_2.setText(_translate("MainWindow", "Страна"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Россия"))
        self.label_3.setText(_translate("MainWindow", "Город"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Москва"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "2010"))
        self.label_4.setText(_translate("MainWindow", "Основан"))
        self.label_5.setText(_translate("MainWindow", "Телефон"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "8909 123 45 67"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "info@mail.ru"))
        self.label_7.setText(_translate("MainWindow", "Описание"))
        self.tableWidgetPublic.setSortingEnabled(True)
        item = self.tableWidgetPublic.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetPublic.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.publisher), _translate("MainWindow", "Издатели"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Книга"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Дата выдачи"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Дата возврата"))
        self.groupBoxEx.setTitle(_translate("MainWindow", "Выдача книг"))
        self.label_8.setText(_translate("MainWindow", "Книга:"))
        self.label_9.setText(_translate("MainWindow", "Читатель:"))
        self.label_10.setText(_translate("MainWindow", "Дата выдачи:"))
        self.pushButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.groupBox_Rec.setTitle(_translate("MainWindow", "Возврат книг"))

        self.label_16.setText(_translate("MainWindow", "Дата возврата:"))
        self.pushButton_4.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delivery), _translate("MainWindow", "Выдача книг"))
        self.label_Kdelete.setText(_translate("MainWindow", "Удалить"))
        self.label_Ksave.setText(_translate("MainWindow", "Сохранить"))
        self.label_Kadd.setText(_translate("MainWindow", "Добавить"))
        self.label_export.setText(_translate("MainWindow", "Экспорт таблицы"))
